src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('urlapp.urls')),
]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/urlapp/urls.py
from django.urls import path
from .import views


app_name = 'urlapp' 

urlpatterns = [
    path('', views.home, name='home'),
    path('create', views.add, name='create'),
    path('<str:pk>', views.shorten, name='shorten'),
]

src/urlapp/models.py
from django.db import models

# Create your models here.

class LinkInfo(models.Model):
	link = models.CharField(max_length=10000)
	link_id = models.CharField(max_length=5)

	def __str__(self):
		return self.link_id

src/src/views.py
from django.shortcuts import render

# Create your views here.
def base(request):
	context ={}
	return render(request, 'base.html')

src/urlapp/views.py
from django.shortcuts import render, redirect
from .models import LinkInfo
import uuid
from django.contrib import messages
#from django.shortcuts import get_object_or_404

# comment = get_object_or_404(Comment, pk=comment_id)

# Create your views here.
def home(request):
	context ={}
	return render(request, 'home.html', context)



def add(request):
	if request.method == 'POST':
		link = request.POST.get('expand')
		link_id = str(uuid.uuid4())[:5]
		link_id = link_id
		url = LinkInfo.objects.filter(link=link)
		if not url :
			url = LinkInfo.objects.create(link=link, link_id=link_id)
			url.save()
		else :
			url = LinkInfo.objects.get(link=link)
			if url.link_id == None:
				url = LinkInfo.objects.get(link=url.link, link_id=link_id)
				url.save()
			else :
				messages.warning(request, 'This link has been entered!')
				url = LinkInfo.objects.get(link=link)
		context = {'url':url}
		return render(request, 'home.html', context)


def shorten(request,pk):
	link_id = LinkInfo.objects.get(link_id=pk)
	return redirect(link_id.link)

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <title>Url Shortener</title>
</head>
<body>

<main>
  <h1>URL Shortener</h1>
  <form method="post" class="form" action="{% url 'urlapp:create' %}">
    {% csrf_token %}
    <input type="text" id="input" name="expand" placeholder="Enter URL here">
    <div class="buttons">
      <button id="shorten">Shorten</button>
    </div>
    <div>
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
         <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
    <div class="container">
      {% if url %}
        <section class="sec2" name="section1" id="section1">{{url.link}}</section>
        <section class="sec2" name="section2" id="section2">{{url.link_id}}</section>
      {% else %}
        <section class="sec2" name="section1" id="section1"></section>
        <section class="sec2" name="section2" id="section2"></section>
      {% endif %}
  </form>
</main>
    <script src="{% static 'js/script.js' %}"></script>!
</body>
</html>

src/urlapp/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <title>Url Shortener</title>
</head>
<body>

<main>
  <h1>URL Shortener</h1>
  <form method="post" class="form" action="{% url 'urlapp:create' %}">
    {% csrf_token %}
    <input type="text" id="input" name="expand" placeholder="Enter URL here">
    <div class="buttons">
      <button id="shorten">Shorten</button>
    </div>
    <div>
      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
         <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </div>
    <div class="container">
      {% if url %}
        <section class="sec2" name="section1" id="section1">{{url.link}}</section>
        <section class="sec2" name="section2" id="section2">http://localhost:8000/{{url.link_id}}</section>
      {% else %}
        <section class="sec2" name="section1" id="section1"></section>
        <section class="sec2" name="section2" id="section2"></section>
      {% endif %}
  </form>
</main>
    <script src="{% static 'js/script.js' %}"></script>!
</body>
</html>